# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\cmake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\C++Code\takeoff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\C++Code\takeoff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:\cmake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\cmake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\C++Code\takeoff\CMakeFiles D:\C++Code\takeoff\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\C++Code\takeoff\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HexGen

# Build rule for target.
HexGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 HexGen
.PHONY : HexGen

# fast build rule for target.
HexGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/build
.PHONY : HexGen/fast

HexGen.obj: HexGen.cpp.obj
.PHONY : HexGen.obj

# target to build an object file
HexGen.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/HexGen.cpp.obj
.PHONY : HexGen.cpp.obj

HexGen.i: HexGen.cpp.i
.PHONY : HexGen.i

# target to preprocess a source file
HexGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/HexGen.cpp.i
.PHONY : HexGen.cpp.i

HexGen.s: HexGen.cpp.s
.PHONY : HexGen.s

# target to generate assembly for a file
HexGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/HexGen.cpp.s
.PHONY : HexGen.cpp.s

Main.obj: Main.cpp.obj
.PHONY : Main.obj

# target to build an object file
Main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/Main.cpp.obj
.PHONY : Main.cpp.obj

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/Main.cpp.s
.PHONY : Main.cpp.s

Mesh.obj: Mesh.cpp.obj
.PHONY : Mesh.obj

# target to build an object file
Mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/Mesh.cpp.obj
.PHONY : Mesh.cpp.obj

Mesh.i: Mesh.cpp.i
.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s
.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\HexGen.dir\build.make CMakeFiles/HexGen.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... HexGen
	@echo ... HexGen.obj
	@echo ... HexGen.i
	@echo ... HexGen.s
	@echo ... Main.obj
	@echo ... Main.i
	@echo ... Main.s
	@echo ... Mesh.obj
	@echo ... Mesh.i
	@echo ... Mesh.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

